// <auto-generated />
using System;
using Callsign.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Callsign.Core.Migrations
{
    [DbContext(typeof(CallsignDbContext))]
    [Migration("20260820210831_AddOperatingReputation")]
    partial class AddOperatingReputation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Callsign.Core.Domain.AchievementAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("EarnedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Key")
                        .IsUnique();

                    b.ToTable("AchievementAwards");
                });

            modelBuilder.Entity("Callsign.Core.Domain.AircraftInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AcquiredAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AirframeHours")
                        .HasColumnType("REAL");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineConditionMilli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HullConditionMilli")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Last100hHoursWatermark")
                        .HasColumnType("REAL");

                    b.Property<long?>("LastAnnualAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<double>("MaintenanceHoursWatermark")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ownership")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PurchasePriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tail")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TypeId");

                    b.ToTable("AircraftInstances");
                });

            modelBuilder.Entity("Callsign.Core.Domain.AircraftTitleAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AircraftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AircraftTypeId");

                    b.HasIndex("TitleNormalized");

                    b.ToTable("AircraftTitleAliases");
                });

            modelBuilder.Entity("Callsign.Core.Domain.AircraftType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CruiseKtas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FuelCapacityLbs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IcaoModel")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("IcaoTypeDesignator")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinRunwayFt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UiTypeRole")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsefulLoadLbs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AircraftTypes");
                });

            modelBuilder.Entity("Callsign.Core.Domain.AirlineReputationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalanceMilli")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeltaMilli")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "At");

                    b.ToTable("AirlineReputationEvents");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Airport", b =>
                {
                    b.Property<string>("Ident")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElevationFt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IataCode")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("IcaoCode")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("IsoCountry")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("IsoRegion")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("LongestRunwayFt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Municipality")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ScheduledService")
                        .HasColumnType("INTEGER");

                    b.HasKey("Ident");

                    b.HasIndex("IcaoCode");

                    b.HasIndex("IsoCountry");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Base", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirportIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FuelFarmLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastRentBilledAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaintenanceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OpenedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RentPerDayCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "AirportIcao")
                        .IsUnique();

                    b.ToTable("Bases");
                });

            modelBuilder.Entity("Callsign.Core.Domain.CampaignProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StepStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "CampaignKey")
                        .IsUnique();

                    b.ToTable("CampaignProgress");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastJobAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoyaltyMilli")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ClientKey")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColorHex")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("AirlineName")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<long>("CashCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmblemKey")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatingReputationMilli")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TailCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AircraftInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AircraftTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AircraftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApproachScore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArrivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComfortScore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistanceNm")
                        .HasColumnType("REAL");

                    b.Property<Guid>("FlownByPilotId")
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelUsedLbs")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("JobAssignmentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LandingScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutcomeGrade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutcomeReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OverallScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayoutBreakdownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PayoutCents")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ScoreValid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SettledAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("StabilizedApproach")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TouchdownFpm")
                        .HasColumnType("REAL");

                    b.Property<double?>("TouchdownFpmWorst3")
                        .HasColumnType("REAL");

                    b.Property<double?>("TouchdownG")
                        .HasColumnType("REAL");

                    b.Property<int?>("ViolationPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftInstanceId");

                    b.HasIndex("FlownByPilotId");

                    b.HasIndex("JobAssignmentId")
                        .IsUnique();

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Callsign.Core.Domain.FlightEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId", "Seq");

                    b.ToTable("FlightEvents");
                });

            modelBuilder.Entity("Callsign.Core.Domain.InstalledPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AircraftFolder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AircraftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HostClientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnDisk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageFolder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ScannedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AircraftTypeId");

                    b.ToTable("InstalledPackages");
                });

            modelBuilder.Entity("Callsign.Core.Domain.InsurancePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AircraftInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoverageMilli")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DeductibleCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HullValueCents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PremiumLastBilledAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PremiumPerWeekCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftInstanceId");

                    b.HasIndex("CompanyId");

                    b.ToTable("InsurancePolicies");
                });

            modelBuilder.Entity("Callsign.Core.Domain.InventoryLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AcquiredAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Good")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitCostCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Good", "LocationIcao");

                    b.ToTable("InventoryLots");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientKey")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceNm")
                        .HasColumnType("REAL");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GeneratedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LoadByAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredRank")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RewardCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceRouteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightLbs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginIcao", "ExpiresAt");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Callsign.Core.Domain.JobAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AcceptedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientKey")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeadlineAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceNm")
                        .HasColumnType("REAL");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pax")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RewardQuoteCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SettledAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeightLbs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpQuote")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JobId");

                    b.ToTable("JobAssignments");
                });

            modelBuilder.Entity("Callsign.Core.Domain.LedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AircraftInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("BaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryUid")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedEntityType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryUid")
                        .IsUnique();

                    b.HasIndex("AccountId", "At");

                    b.HasIndex("AccountId", "DedupeKey")
                        .IsUnique();

                    b.HasIndex("AircraftInstanceId", "At");

                    b.HasIndex("BaseId", "At");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId");

                    b.HasIndex("StaffId", "At");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AprBps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DelinquentSinceAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OutstandingCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PaymentLastBilledAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrincipalCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("TakenAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TermDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Callsign.Core.Domain.MarketPressure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Good")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<long>("PressureLbs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Icao", "Good")
                        .IsUnique();

                    b.ToTable("MarketPressures");
                });

            modelBuilder.Entity("Callsign.Core.Domain.OperatingCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IssuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Kind")
                        .IsUnique();

                    b.ToTable("OperatingCertificates");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Pilot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentIcao")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeIcao")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReputationMilli")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("Callsign.Core.Domain.PilotQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("BestTouchdownFpm")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("CheckFlightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<long>("EarnedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PilotId", "Class")
                        .IsUnique();

                    b.ToTable("PilotQualifications");
                });

            modelBuilder.Entity("Callsign.Core.Domain.RentalAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AircraftInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BuyoutCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DepositCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngineMilliAtPickup")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FlightHourRateCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HoldingPerDayCents")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HoursAtPickup")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursLastBilled")
                        .HasColumnType("REAL");

                    b.Property<int>("HullMilliAtPickup")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InsuranceWeeklyCents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastRentBilledAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RentCreditedCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SloppyEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WeeklyRateCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftInstanceId");

                    b.HasIndex("CompanyId");

                    b.ToTable("RentalAgreements");
                });

            modelBuilder.Entity("Callsign.Core.Domain.ReputationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalanceMilli")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeltaMilli")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PilotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PilotId", "At");

                    b.ToTable("ReputationEvents");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AircraftInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceNm")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastReconciledAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceMultiplierMilli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.Property<long>("RewardPerTripCents")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RoundTripHours")
                        .HasColumnType("REAL");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftInstanceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StaffId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Runway", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirportIdent")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeIdent")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeIdent")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LengthFt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Lighted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surface")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WidthFt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirportIdent");

                    b.ToTable("Runways");
                });

            modelBuilder.Entity("Callsign.Core.Domain.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("HiredAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastPaidAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillMilli")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WagePerDayCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Callsign.Core.Domain.StandingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AircraftInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceNm")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastReconciledAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OriginClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginIcao")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceMultiplierMilli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.Property<long>("RewardPerTripCents")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RoundTripHours")
                        .HasColumnType("REAL");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightLbs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftInstanceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StaffId");

                    b.ToTable("StandingOrders");
                });

            modelBuilder.Entity("Callsign.Core.Domain.AchievementAward", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.AircraftInstance", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Callsign.Core.Domain.AircraftType", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.AircraftTitleAlias", b =>
                {
                    b.HasOne("Callsign.Core.Domain.AircraftType", null)
                        .WithMany("Aliases")
                        .HasForeignKey("AircraftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.AirlineReputationEvent", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.Base", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.CampaignProgress", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.Client", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.InstalledPackage", b =>
                {
                    b.HasOne("Callsign.Core.Domain.AircraftType", null)
                        .WithMany()
                        .HasForeignKey("AircraftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.InsurancePolicy", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.InventoryLot", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.LedgerEntry", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.Loan", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.MarketPressure", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.OperatingCertificate", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.Pilot", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.PilotQualification", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Pilot", null)
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.RentalAgreement", b =>
                {
                    b.HasOne("Callsign.Core.Domain.AircraftInstance", null)
                        .WithMany()
                        .HasForeignKey("AircraftInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.ReputationEvent", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Pilot", null)
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.Route", b =>
                {
                    b.HasOne("Callsign.Core.Domain.AircraftInstance", null)
                        .WithMany()
                        .HasForeignKey("AircraftInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Callsign.Core.Domain.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.Runway", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Airport", null)
                        .WithMany()
                        .HasForeignKey("AirportIdent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.Staff", b =>
                {
                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.StandingOrder", b =>
                {
                    b.HasOne("Callsign.Core.Domain.AircraftInstance", null)
                        .WithMany()
                        .HasForeignKey("AircraftInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Callsign.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Callsign.Core.Domain.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Callsign.Core.Domain.AircraftType", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
